name: KingdomsOfArden-Bounties
main: net.kingdomsofarden.andrew2060.bounties.Bounties
load: POSTWORLD
version: 1.10
description: Allows bounties through commands.
depend: [Vault]
commands:
  bounty:
    description: KingdomsOfArden-Bounties Commands
    usage: /<command>
