name: Swagserv-Bounties
main: net.swagserv.jones12.swagservbounties.Bounties
load: POSTWORLD
version: 0.04-Dev
description: Allows bounties through sign commands.
depend: [Vault]
commands:
  bounty:
    description: Swagserv-Bounties Commands
    usage: /<command>
