name: Swagserv-Bounties
main: net.swagserv.andrew2060.swagservbounties.Bounties
load: POSTWORLD
version: 0.06-Dev
description: Allows bounties through commands.
depend: [Vault]
commands:
  bounty:
    description: Swagserv-Bounties Commands
    usage: /<command>
